from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from typing import List
import uvicorn
import os
from pathlib import Path

# Import settings
from config import get_settings

settings = get_settings()

# Database setup
DATABASE_URL = settings.database_url

# Create data directory if not exists
db_path = Path(settings.database_url.replace("sqlite:///", ""))
if not db_path.parent.exists():
    db_path.parent.mkdir(parents=True)

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False},
    pool_size=settings.database_pool_size,
    max_overflow=settings.database_max_overflow
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# Database model
class Item(Base):
    __tablename__ = "items"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, index=True)
    description = Column(String)

# Create tables
Base.metadata.create_all(bind=engine)

# Pydantic models
class ItemCreate(BaseModel):
    name: str
    description: str | None = None

class ItemResponse(BaseModel):
    id: int
    name: str
    description: str | None = None
    
    class Config:
        from_attributes = True

# FastAPI app
app = FastAPI(
    title=settings.app_name,
    description=f"Generated by DevMate - {settings.app_version}",
    version=settings.app_version,
    debug=settings.debug
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=settings.cors_allow_credentials,
    allow_methods=settings.cors_allow_methods_list,
    allow_headers=settings.cors_allow_headers_list,
)

# Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/")
def read_root():
    return {
        "message": f"Welcome to {settings.app_name} API",
        "status": "running",
        "version": settings.app_version
    }

@app.get("/api/data")
def get_data():
    """Get sample data from database"""
    db = SessionLocal()
    try:
        items = db.query(Item).limit(10).all()
        return [{"id": item.id, "name": item.name, "description": item.description} for item in items]
    finally:
        db.close()

@app.post("/api/items", response_model=ItemResponse)
def create_item(item: ItemCreate):
    """Create a new item"""
    db = SessionLocal()
    try:
        db_item = Item(name=item.name, description=item.description)
        db.add(db_item)
        db.commit()
        db.refresh(db_item)
        return db_item
    finally:
        db.close()

@app.get("/api/items", response_model=List[ItemResponse])
def get_items():
    """Get all items"""
    db = SessionLocal()
    try:
        items = db.query(Item).all()
        return items
    finally:
        db.close()

if __name__ == "__main__":
    uvicorn.run(
        app,
        host=settings.host,
        port=settings.port,
        log_level=settings.log_level.lower()
    )
