import { useState, useEffect } from 'react'

function App() {
  const [message, setMessage] = useState('')
  const [data, setData] = useState([])
  
  // Use environment variable for API URL with fallback
  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'
  const APP_NAME = import.meta.env.VITE_APP_NAME || 'DevMate App'

  useEffect(() => {
    // Fetch data from backend using environment variable
    fetch(`${API_URL}/api/data`)
      .then(res => res.json())
      .then(data => setData(data))
      .catch(err => console.error('Error fetching data:', err))
  }, [])

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 p-8">
      <div className="max-w-4xl mx-auto">
        <header className="text-center mb-12">
          <h1 className="text-5xl font-bold text-indigo-900 mb-4">
            {APP_NAME}
          </h1>
          <p className="text-lg text-indigo-700">
            Generated by DevMate - Full-Stack AI Developer Agent
          </p>
        </header>

        <div className="bg-white rounded-xl shadow-xl p-8 mb-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">
            ✨ Features
          </h2>
          <ul className="space-y-2 text-gray-600">
            <li>✓ React + Vite + Tailwind CSS</li>
            <li>✓ FastAPI Backend</li>
            <li>✓ SQLite Database</li>
            <li>✓ Hot Reload Enabled</li>
          </ul>
        </div>

        <div className="bg-white rounded-xl shadow-xl p-8">
          <h2 className="text-2xl font-semibold text-gray-800 mb-4">
            🚀 Quick Start
          </h2>
          <div className="space-y-4">
            <div>
              <h3 className="font-medium text-gray-700 mb-2">Frontend:</h3>
              <code className="bg-gray-100 px-3 py-2 rounded text-sm block">
                cd frontend && npm install && npm run dev
              </code>
            </div>
            <div>
              <h3 className="font-medium text-gray-700 mb-2">Backend:</h3>
              <code className="bg-gray-100 px-3 py-2 rounded text-sm block">
                cd backend && pip install -r requirements.txt && uvicorn main:app --reload
              </code>
            </div>
          </div>
        </div>

        {data.length > 0 && (
          <div className="mt-8 bg-white rounded-xl shadow-xl p-8">
            <h2 className="text-2xl font-semibold text-gray-800 mb-4">
              📊 Backend Data
            </h2>
            <pre className="bg-gray-100 p-4 rounded text-sm overflow-auto">
              {JSON.stringify(data, null, 2)}
            </pre>
          </div>
        )}
      </div>
    </div>
  )
}

export default App
