from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from sqlalchemy import create_engine, Column, Integer, String, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from typing import List
import uvicorn
from pathlib import Path

# Import settings
from config import get_settings

settings = get_settings()

# Database setup
DATABASE_URL = settings.database_url

# Create data directory if not exists
db_path = Path(settings.database_url.replace("sqlite:///", ""))
if not db_path.parent.exists():
    db_path.parent.mkdir(parents=True)

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False},
    pool_size=settings.database_pool_size,
    max_overflow=settings.database_max_overflow
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

# Database model
class Todo(Base):
    __tablename__ = "todos"
    
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    description = Column(String)
    completed = Column(Boolean, default=False)

# Create tables
Base.metadata.create_all(bind=engine)

# Pydantic models
class TodoCreate(BaseModel):
    title: str
    description: str | None = None
    completed: bool | None = False

class TodoUpdate(BaseModel):
    title: str | None = None
    description: str | None = None
    completed: bool | None = None

class TodoResponse(BaseModel):
    id: int
    title: str
    description: str | None = None
    completed: bool
    
    class Config:
        from_attributes = True

# FastAPI app
app = FastAPI(
    title=settings.app_name,
    description=f"Generated by DevMate - A todo app with user login and data persistence",
    version=settings.app_version,
    debug=settings.debug
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins_list,
    allow_credentials=settings.cors_allow_credentials,
    allow_methods=settings.cors_allow_methods_list,
    allow_headers=settings.cors_allow_headers_list,
)

# Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/")
def read_root():
    return {
        "message": f"Welcome to {settings.app_name} API",
        "status": "running",
        "version": settings.app_version
    }

@app.get("/api/todos", response_model=List[TodoResponse])
def get_todos():
    """Get all todos"""
    db = SessionLocal()
    try:
        todos = db.query(Todo).all()
        return todos
    finally:
        db.close()

@app.post("/api/todos", response_model=TodoResponse)
def create_todo(todo: TodoCreate):
    """Create a new todo"""
    db = SessionLocal()
    try:
        db_todo = Todo(
            title=todo.title,
            description=todo.description or '',
            completed=todo.completed or False
        )
        db.add(db_todo)
        db.commit()
        db.refresh(db_todo)
        return db_todo
    finally:
        db.close()

@app.put("/api/todos/{todo_id}", response_model=TodoResponse)
def update_todo(todo_id: int, todo_update: TodoUpdate):
    """Update a todo"""
    db = SessionLocal()
    try:
        db_todo = db.query(Todo).filter(Todo.id == todo_id).first()
        if not db_todo:
            raise HTTPException(status_code=404, detail="Todo not found")
        
        if todo_update.title is not None:
            db_todo.title = todo_update.title
        if todo_update.description is not None:
            db_todo.description = todo_update.description
        if todo_update.completed is not None:
            db_todo.completed = todo_update.completed
        
        db.commit()
        db.refresh(db_todo)
        return db_todo
    finally:
        db.close()

@app.delete("/api/todos/{todo_id}")
def delete_todo(todo_id: int):
    """Delete a todo"""
    db = SessionLocal()
    try:
        db_todo = db.query(Todo).filter(Todo.id == todo_id).first()
        if not db_todo:
            raise HTTPException(status_code=404, detail="Todo not found")
        
        db.delete(db_todo)
        db.commit()
        return {"message": "Todo deleted successfully"}
    finally:
        db.close()

if __name__ == "__main__":
    uvicorn.run(
        app,
        host=settings.host,
        port=settings.port,
        log_level=settings.log_level.lower()
    )
